/*
# Extend alerts table with source_type, rule_name, and social_platform

1. Changes
- `source_type` (text) — classifies how the alert was generated:
    'native'  — generated by matching a rule against fire DB data
    'social'  — manually entered from a social media report
    'rss'     — imported from an RSS/external feed (GDACS, FEMA, etc.)
    'manual'  — free-form alert entered directly by a user
  Default: 'native' so existing rows keep their meaning.

- `rule_name` (text) — snapshot of the alert rule's name at generation time.
  Stored at insert so the label survives if the rule is later renamed/deleted.

- `social_platform` (text) — for source_type='social', the platform the
  report came from: 'facebook' | 'twitter' | 'instagram' | 'nextdoor' |
  'youtube' | 'other'.

- `content_url` (text) — optional link to the original social media post or
  external source article.

2. Index
- `alerts_source_type_idx` on (source_type) for the feeds pane filter.

3. Notes
- All existing rows default to source_type='native' via the column default.
- rule_name is null for manually-created alerts and social media alerts not
  tied to a rule.
*/

ALTER TABLE alerts
  ADD COLUMN IF NOT EXISTS source_type text NOT NULL DEFAULT 'native'
    CHECK (source_type IN ('native', 'social', 'rss', 'manual')),
  ADD COLUMN IF NOT EXISTS rule_name text,
  ADD COLUMN IF NOT EXISTS social_platform text
    CHECK (social_platform IS NULL OR social_platform IN (
      'facebook', 'twitter', 'instagram', 'nextdoor', 'youtube', 'other'
    )),
  ADD COLUMN IF NOT EXISTS content_url text;

CREATE INDEX IF NOT EXISTS alerts_source_type_idx ON alerts(source_type);
